name: Bug report
description: Create a report to help improve the extension.
title: "[BUG]"
labels:
  - bug
assignees:
  - kszymukowicz
body:
  - type: input
    id: typo3-version
    attributes:
      label: TYPO3 version
      description: What TYPO3 version are you using?
      placeholder: 'e.g. 12.4.2'
    validations:
      required: true
  - type: input
    id: php-version
    attributes:
      label: PHP version
      description: What PHP version are you using?
      placeholder: 'e.g. 8.3.23'
    validations:
      required: true
  - type: input
    id: extension-version
    attributes:
      label: Extension version
      description: What version of EXT:t3api are you using?
      placeholder: 'e.g. 3.0.1'
    validations:
      required: true
  - type: checkboxes
    id: composer-mode
    attributes:
      label: Composer mode
      description: Are you running TYPO3 in composer mode?
      options:
        - label: I'm running TYPO3 in composer mode.
  - type: input
    id: operating-system
    attributes:
      label: Operating system
      description: What operating system are you using?
      placeholder: 'e.g. macOS 14.5'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current behavior
      description: A clear description of what the bug is.
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear description of what you expected to happen.
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: If possible, describe steps to reproduce the behavior.
      placeholder: |
        1. [First Step]
        2. [Second Step]
        3. [and so on...]
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: >
        By submitting this issue, you agree to follow our
        [Code of Conduct](https://github.com/sourcebroker/t3api/blob/main/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct.
          required: true
  - type: markdown
    attributes:
      value: >
        :bulb: **Tip:** Have you already looked into our https://github.com/sourcebroker/t3api/discussions/categories/q-a?
        Maybe your problem has already been discussed there.
