#!/bin/bash

## Description: [ExtDev] Run matrix tests for TYPO3_VERSIONS, PHP_VERSIONS and composer "lowest/highest".
## Usage: "ci"
## Example: "ddev ci" or "ddev ci all" or "ddev ci 12 8.3 lowest"

set -e

source .ddev/test/utils.sh
export_ddev_env_vars

trap 'restoreComposerFiles' SIGINT SIGTERM

ci_single() {
    TYPO3=$1
    PHP=$2
    COMPOSER=${3:-highest}

    if [ -z "$TYPO3" ]; then
        TYPO3=$(get_lowest_supported_typo3_versions)
    else
        if ! check_typo3_version "$TYPO3"; then
            exit 1
        fi
    fi

    if [ -z "$PHP" ]; then
        PHP=$(get_lowest_supported_php_versions_for_typo3 "$TYPO3")
    else
        if ! check_php_version_for_typo3 "$TYPO3" "$PHP"; then
            exit 1
        fi
    fi

    if [[ "$COMPOSER" != "lowest" && "$COMPOSER" != "highest" ]]; then
        message red "Invalid third argument. COMPOSER value can only be 'lowest' or 'highest'."
        exit 1
    fi

    message magenta "-------------------------------------------------"
    message magenta "| TYPO3 \t| PHP\t\t| Composer\t|"
    message magenta "-------------------------------------------------"
    message magenta "| $TYPO3\t\t| $PHP\t\t| $COMPOSER\t|"
    message magenta "-------------------------------------------------"
    message magenta ""

    ddev config --php-version="$PHP"
    ddev restart

    if [ -n "$GH_TOKEN" ] && ! ddev composer config --global --list | grep -q "github-oauth.github.com"; then
      message magenta "Add GH_TOKEN to composer github-oauth.github.com after 'ddev ci' internal ddev restart"
      ddev composer config --global github-oauth.github.com "${GH_TOKEN}"
    fi

    stashComposerFiles
    ddev composer require --no-ansi --no-interaction --no-progress --no-update typo3/cms-core:^${TYPO3} || exit 1
    if [ "$COMPOSER" == "lowest" ]; then
        ddev exec composer update --prefer-lowest --prefer-stable --with-dependencies --no-progress --no-interaction || exit 1
    else
        ddev exec composer update --with-dependencies --no-progress --no-interaction || exit 1
    fi
    message magenta "ddev composer normalize"
    ddev composer normalize
    message magenta "ddev install $TYPO3"
    ddev install "$TYPO3"
    message magenta "composer ci"
    ddev composer ci
    restoreComposerFiles
}

if [ $# -eq 0 ]; then
    ddev composer ci
    ddev docs ci
    exit 0
fi

TYPO3=${1}

if [ "$TYPO3" == "all" ]; then
    COMPOSER_INSTALLS=("lowest" "highest")

    TYPO3_VERSIONS_ARRAY=()
    while IFS= read -r line; do
        TYPO3_VERSIONS_ARRAY+=("$line")
    done < <(get_supported_typo3_versions)

    for TYPO3 in "${TYPO3_VERSIONS_ARRAY[@]}"; do
        PHP_VERSIONS=()
        while IFS= read -r line; do
            PHP_VERSIONS+=("$line")
        done < <(get_supported_php_versions_for_typo3 "$TYPO3")
        for PHP in "${PHP_VERSIONS[@]}"; do
            for COMPOSER in "${COMPOSER_INSTALLS[@]}"; do
                ci_single "$TYPO3" "$PHP" "$COMPOSER"
            done
        done
    done
    ddev docs ci
else
    PHP=${2}
    COMPOSER=${3}
    ci_single "$TYPO3" "$PHP" "$COMPOSER"
    ddev docs ci
fi
