#!/bin/bash

## Description: Build docs.
## Usage: "docs"
## Example: "ddev docs"

docker run --rm --pull always -v ./:/project/ ghcr.io/typo3-documentation/render-guides:latest --no-progress --config Documentation Documentation
