#!/bin/bash

## Description: Run matrix tests from TYPO3_VERSIONS, TYPO3_VERSIONS_[x]_PHP, composer "lowest/highest".
## Usage: "test"
## Example: "ddev test" or "ddev test all" or "ddev test 12 8.3 lowest"

set -e

source .ddev/test/utils.sh
export_ddev_env_vars

TYPO3=${1}

if [ "$TYPO3" == "all" ]; then
    COMPOSER_INSTALLS=("lowest" "highest")

    TYPO3_VERSIONS_ARRAY=()
    while IFS= read -r line; do
        TYPO3_VERSIONS_ARRAY+=("$line")
    done < <(get_supported_typo3_versions)

    for TYPO3 in "${TYPO3_VERSIONS_ARRAY[@]}"; do
        PHP_VERSIONS=()
        while IFS= read -r line; do
            PHP_VERSIONS+=("$line")
        done < <(get_supported_php_versions_for_typo3 "$TYPO3")
        for PHP in "${PHP_VERSIONS[@]}"; do
            for COMPOSER in "${COMPOSER_INSTALLS[@]}"; do
                .ddev/commands/host/.test-single "$TYPO3" "$PHP" "$COMPOSER"
            done
        done
    done
else
    PHP=${2}
    COMPOSER=${3}
    .ddev/commands/host/.test-single "$TYPO3" "$PHP" "$COMPOSER"
fi
