#!/bin/bash

set -e

function echo_magenta() {
    echo -e "\033[35m$1\033[0m"
}

PHP_VERSIONS=("8.1" "8.2" "8.3")
COMPOSER_INSTALLS=("composerInstallLowest" "composerInstallHighest")
TYPO3_VERSIONS=("12")

for PHP in "${PHP_VERSIONS[@]}"; do
    for COMPOSER in "${COMPOSER_INSTALLS[@]}"; do
        for TYPO3 in "${TYPO3_VERSIONS[@]}"; do

            echo_magenta "----------------------------------------------------------------------"
            echo_magenta " PHP Version\t| Composer Install\t\t| TYPO3 Version\t|"
            echo_magenta "----------------------------------------------------------------------"
            echo_magenta " $PHP\t\t| $COMPOSER\t\t| $TYPO3\t\t|"
            echo_magenta "----------------------------------------------------------------------"
            echo_magenta ""
            ddev config --php-version=$PHP
            ddev restart
            ddev exec composer config platform.php "$PHP"
            if [ "$COMPOSER" == "composerInstallLowest" ]; then
                ddev exec composer update --prefer-lowest --prefer-stable
            else
                ddev exec composer update
            fi
            ddev composer normalize
            ddev install-v$TYPO3
            ddev composer ci
        done
    done
done
#ddev git checkout -- .ddev/config.yaml
