-- Adminer 4.7.6 MySQL dump

SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;

INSERT INTO `pages` (`uid`, `pid`, `tstamp`, `crdate`, `cruser_id`, `deleted`, `hidden`, `starttime`, `endtime`, `fe_group`, `sorting`, `rowDescription`, `editlock`, `sys_language_uid`, `l10n_parent`, `l10n_source`, `l10n_state`, `t3_origuid`, `l10n_diffsource`, `t3ver_oid`, `t3ver_wsid`, `t3ver_state`, `t3ver_stage`, `t3ver_count`, `t3ver_tstamp`, `t3ver_move_id`, `perms_userid`, `perms_groupid`, `perms_user`, `perms_group`, `perms_everybody`, `title`, `slug`, `doktype`, `TSconfig`, `is_siteroot`, `php_tree_stop`, `url`, `shortcut`, `shortcut_mode`, `subtitle`, `layout`, `target`, `media`, `lastUpdated`, `keywords`, `cache_timeout`, `cache_tags`, `newUntil`, `description`, `no_search`, `SYS_LASTCHANGED`, `abstract`, `module`, `extendToSubpages`, `author`, `author_email`, `nav_title`, `nav_hide`, `content_from_pid`, `mount_pid`, `mount_pid_ol`, `l18n_cfg`, `fe_login_mode`, `backend_layout`, `backend_layout_next_level`, `tsconfig_includes`, `legacy_overlay_uid`, `categories`) VALUES
(1,	0,	1590250026,	1590184366,	1,	0,	0,	0,	0,	'',	0,	NULL,	0,	0,	0,	0,	NULL,	0,	'a:37:{s:7:\"doktype\";N;s:5:\"title\";N;s:4:\"slug\";N;s:9:\"nav_title\";N;s:8:\"subtitle\";N;s:8:\"abstract\";N;s:8:\"keywords\";N;s:11:\"description\";N;s:6:\"author\";N;s:12:\"author_email\";N;s:11:\"lastUpdated\";N;s:6:\"layout\";N;s:8:\"newUntil\";N;s:14:\"backend_layout\";N;s:25:\"backend_layout_next_level\";N;s:16:\"content_from_pid\";N;s:6:\"target\";N;s:13:\"cache_timeout\";N;s:10:\"cache_tags\";N;s:11:\"is_siteroot\";N;s:9:\"no_search\";N;s:13:\"php_tree_stop\";N;s:6:\"module\";N;s:5:\"media\";N;s:17:\"tsconfig_includes\";N;s:8:\"TSconfig\";N;s:8:\"l18n_cfg\";N;s:6:\"hidden\";N;s:8:\"nav_hide\";N;s:9:\"starttime\";N;s:7:\"endtime\";N;s:16:\"extendToSubpages\";N;s:8:\"fe_group\";N;s:13:\"fe_login_mode\";N;s:8:\"editlock\";N;s:10:\"categories\";N;s:14:\"rowDescription\";N;}',	0,	0,	0,	0,	0,	0,	0,	1,	1,	31,	31,	1,	'Home',	'/',	1,	NULL,	1,	0,	'',	0,	0,	'',	0,	'',	0,	0,	NULL,	0,	'',	0,	NULL,	0,	1590250026,	NULL,	'',	0,	'',	'',	'',	0,	0,	0,	0,	0,	0,	'',	'',	NULL,	0,	0),
(2,	1,	1590250041,	1590185724,	1,	0,	0,	0,	0,	'',	256,	'',	0,	0,	0,	0,	NULL,	0,	'a:37:{s:7:\"doktype\";N;s:5:\"title\";N;s:4:\"slug\";N;s:9:\"nav_title\";N;s:8:\"subtitle\";N;s:8:\"abstract\";N;s:8:\"keywords\";N;s:11:\"description\";N;s:6:\"author\";N;s:12:\"author_email\";N;s:11:\"lastUpdated\";N;s:6:\"layout\";N;s:8:\"newUntil\";N;s:14:\"backend_layout\";N;s:25:\"backend_layout_next_level\";N;s:16:\"content_from_pid\";N;s:6:\"target\";N;s:13:\"cache_timeout\";N;s:10:\"cache_tags\";N;s:11:\"is_siteroot\";N;s:9:\"no_search\";N;s:13:\"php_tree_stop\";N;s:6:\"module\";N;s:5:\"media\";N;s:17:\"tsconfig_includes\";N;s:8:\"TSconfig\";N;s:8:\"l18n_cfg\";N;s:6:\"hidden\";N;s:8:\"nav_hide\";N;s:9:\"starttime\";N;s:7:\"endtime\";N;s:16:\"extendToSubpages\";N;s:8:\"fe_group\";N;s:13:\"fe_login_mode\";N;s:8:\"editlock\";N;s:10:\"categories\";N;s:14:\"rowDescription\";N;}',	0,	0,	0,	0,	0,	0,	0,	1,	0,	31,	27,	0,	'Page 1',	'/page-1',	1,	'',	0,	0,	'',	0,	0,	'',	0,	'',	0,	0,	'',	0,	'',	0,	'',	0,	0,	'',	'',	0,	'',	'',	'',	0,	0,	0,	0,	0,	0,	'',	'',	'',	0,	0),
(3,	1,	1590836027,	1590250003,	1,	0,	0,	0,	0,	'0',	512,	NULL,	0,	0,	0,	0,	NULL,	0,	'a:1:{s:5:\"title\";N;}',	0,	0,	0,	0,	0,	0,	0,	1,	0,	31,	27,	0,	'News A',	'/sys-folder/news',	254,	NULL,	0,	0,	'',	0,	0,	'',	0,	'',	0,	0,	NULL,	0,	'',	0,	NULL,	0,	0,	NULL,	'',	0,	'',	'',	'',	0,	0,	0,	0,	0,	0,	'',	'',	NULL,	0,	0),
(4,	1,	1590705047,	1590705030,	1,	0,	0,	0,	0,	'0',	384,	NULL,	0,	0,	0,	0,	NULL,	0,	'a:1:{s:6:\"hidden\";N;}',	0,	0,	0,	0,	0,	0,	0,	1,	0,	31,	27,	0,	'Page 2',	'/page-2',	1,	NULL,	0,	0,	'',	0,	0,	'',	0,	'',	0,	0,	NULL,	0,	'',	0,	NULL,	0,	0,	NULL,	'',	0,	'',	'',	'',	0,	0,	0,	0,	0,	0,	'',	'',	NULL,	0,	0),
(5,	1,	1590705042,	1590705037,	1,	0,	0,	0,	0,	'0',	448,	NULL,	0,	0,	0,	0,	NULL,	0,	'a:1:{s:6:\"hidden\";N;}',	0,	0,	0,	0,	0,	0,	0,	1,	0,	31,	27,	0,	'Page 3',	'/page-3',	1,	NULL,	0,	0,	'',	0,	0,	'',	0,	'',	0,	0,	NULL,	0,	'',	0,	NULL,	0,	0,	NULL,	'',	0,	'',	'',	'',	0,	0,	0,	0,	0,	0,	'',	'',	NULL,	0,	0),
(6,	1,	1590836092,	1590836046,	1,	0,	0,	0,	0,	'',	768,	NULL,	0,	0,	0,	0,	NULL,	3,	'a:1:{s:6:\"hidden\";N;}',	0,	0,	0,	0,	0,	0,	0,	1,	0,	31,	27,	0,	'News B',	'/sys-folder/news-1',	254,	NULL,	0,	0,	'',	0,	0,	'',	0,	'',	0,	0,	NULL,	0,	'',	0,	NULL,	0,	0,	NULL,	'',	0,	'',	'',	'',	0,	0,	0,	0,	0,	0,	'',	'',	'',	0,	0)
ON DUPLICATE KEY UPDATE `uid` = VALUES(`uid`), `pid` = VALUES(`pid`), `tstamp` = VALUES(`tstamp`), `crdate` = VALUES(`crdate`), `cruser_id` = VALUES(`cruser_id`), `deleted` = VALUES(`deleted`), `hidden` = VALUES(`hidden`), `starttime` = VALUES(`starttime`), `endtime` = VALUES(`endtime`), `fe_group` = VALUES(`fe_group`), `sorting` = VALUES(`sorting`), `rowDescription` = VALUES(`rowDescription`), `editlock` = VALUES(`editlock`), `sys_language_uid` = VALUES(`sys_language_uid`), `l10n_parent` = VALUES(`l10n_parent`), `l10n_source` = VALUES(`l10n_source`), `l10n_state` = VALUES(`l10n_state`), `t3_origuid` = VALUES(`t3_origuid`), `l10n_diffsource` = VALUES(`l10n_diffsource`), `t3ver_oid` = VALUES(`t3ver_oid`), `t3ver_wsid` = VALUES(`t3ver_wsid`), `t3ver_state` = VALUES(`t3ver_state`), `t3ver_stage` = VALUES(`t3ver_stage`), `t3ver_count` = VALUES(`t3ver_count`), `t3ver_tstamp` = VALUES(`t3ver_tstamp`), `t3ver_move_id` = VALUES(`t3ver_move_id`), `perms_userid` = VALUES(`perms_userid`), `perms_groupid` = VALUES(`perms_groupid`), `perms_user` = VALUES(`perms_user`), `perms_group` = VALUES(`perms_group`), `perms_everybody` = VALUES(`perms_everybody`), `title` = VALUES(`title`), `slug` = VALUES(`slug`), `doktype` = VALUES(`doktype`), `TSconfig` = VALUES(`TSconfig`), `is_siteroot` = VALUES(`is_siteroot`), `php_tree_stop` = VALUES(`php_tree_stop`), `url` = VALUES(`url`), `shortcut` = VALUES(`shortcut`), `shortcut_mode` = VALUES(`shortcut_mode`), `subtitle` = VALUES(`subtitle`), `layout` = VALUES(`layout`), `target` = VALUES(`target`), `media` = VALUES(`media`), `lastUpdated` = VALUES(`lastUpdated`), `keywords` = VALUES(`keywords`), `cache_timeout` = VALUES(`cache_timeout`), `cache_tags` = VALUES(`cache_tags`), `newUntil` = VALUES(`newUntil`), `description` = VALUES(`description`), `no_search` = VALUES(`no_search`), `SYS_LASTCHANGED` = VALUES(`SYS_LASTCHANGED`), `abstract` = VALUES(`abstract`), `module` = VALUES(`module`), `extendToSubpages` = VALUES(`extendToSubpages`), `author` = VALUES(`author`), `author_email` = VALUES(`author_email`), `nav_title` = VALUES(`nav_title`), `nav_hide` = VALUES(`nav_hide`), `content_from_pid` = VALUES(`content_from_pid`), `mount_pid` = VALUES(`mount_pid`), `mount_pid_ol` = VALUES(`mount_pid_ol`), `l18n_cfg` = VALUES(`l18n_cfg`), `fe_login_mode` = VALUES(`fe_login_mode`), `backend_layout` = VALUES(`backend_layout`), `backend_layout_next_level` = VALUES(`backend_layout_next_level`), `tsconfig_includes` = VALUES(`tsconfig_includes`), `legacy_overlay_uid` = VALUES(`legacy_overlay_uid`), `categories` = VALUES(`categories`);

INSERT INTO `sys_category` (`uid`, `pid`, `tstamp`, `crdate`, `cruser_id`, `deleted`, `hidden`, `starttime`, `endtime`, `sorting`, `description`, `sys_language_uid`, `l10n_parent`, `l10n_state`, `t3_origuid`, `l10n_diffsource`, `t3ver_oid`, `t3ver_wsid`, `t3ver_state`, `t3ver_stage`, `t3ver_count`, `t3ver_tstamp`, `t3ver_move_id`, `title`, `parent`, `items`, `fe_group`, `images`, `single_pid`, `shortcut`, `import_id`, `import_source`, `seo_title`, `seo_description`, `seo_headline`, `seo_text`, `slug`) VALUES
(1,	3,	1590836114,	1590700984,	1,	0,	0,	0,	0,	256,	'',	0,	0,	NULL,	0,	'a:16:{s:5:\"title\";N;s:4:\"slug\";N;s:6:\"parent\";N;s:5:\"items\";N;s:16:\"sys_language_uid\";N;s:6:\"hidden\";N;s:9:\"starttime\";N;s:7:\"endtime\";N;s:9:\"seo_title\";N;s:15:\"seo_description\";N;s:12:\"seo_headline\";N;s:8:\"seo_text\";N;s:6:\"images\";N;s:11:\"description\";N;s:10:\"single_pid\";N;s:8:\"shortcut\";N;}',	0,	0,	0,	0,	0,	0,	0,	'Category 1A',	0,	1,	'0',	0,	0,	0,	'',	'',	'',	'',	'',	'',	'category-1a'),
(2,	3,	1590836129,	1590700995,	1,	0,	0,	0,	0,	512,	'',	0,	0,	NULL,	0,	'a:16:{s:5:\"title\";N;s:4:\"slug\";N;s:6:\"parent\";N;s:5:\"items\";N;s:16:\"sys_language_uid\";N;s:6:\"hidden\";N;s:9:\"starttime\";N;s:7:\"endtime\";N;s:9:\"seo_title\";N;s:15:\"seo_description\";N;s:12:\"seo_headline\";N;s:8:\"seo_text\";N;s:6:\"images\";N;s:11:\"description\";N;s:10:\"single_pid\";N;s:8:\"shortcut\";N;}',	0,	0,	0,	0,	0,	0,	0,	'Category 2A',	0,	2,	'0',	0,	0,	0,	'',	'',	'',	'',	'',	'',	'category-2a'),
(3,	3,	1590836141,	1590701005,	1,	0,	0,	0,	0,	768,	'',	0,	0,	NULL,	0,	'a:16:{s:5:\"title\";N;s:4:\"slug\";N;s:6:\"parent\";N;s:5:\"items\";N;s:16:\"sys_language_uid\";N;s:6:\"hidden\";N;s:9:\"starttime\";N;s:7:\"endtime\";N;s:9:\"seo_title\";N;s:15:\"seo_description\";N;s:12:\"seo_headline\";N;s:8:\"seo_text\";N;s:6:\"images\";N;s:11:\"description\";N;s:10:\"single_pid\";N;s:8:\"shortcut\";N;}',	0,	0,	0,	0,	0,	0,	0,	'Category 3A',	0,	1,	'0',	0,	0,	0,	'',	'',	'',	'',	'',	'',	'category-3a'),
(4,	3,	1590836162,	1590701015,	1,	0,	0,	0,	0,	1024,	'',	0,	0,	NULL,	0,	'a:16:{s:5:\"title\";N;s:4:\"slug\";N;s:6:\"parent\";N;s:5:\"items\";N;s:16:\"sys_language_uid\";N;s:6:\"hidden\";N;s:9:\"starttime\";N;s:7:\"endtime\";N;s:9:\"seo_title\";N;s:15:\"seo_description\";N;s:12:\"seo_headline\";N;s:8:\"seo_text\";N;s:6:\"images\";N;s:11:\"description\";N;s:10:\"single_pid\";N;s:8:\"shortcut\";N;}',	0,	0,	0,	0,	0,	0,	0,	'Category 4A',	0,	1,	'0',	0,	0,	0,	'',	'',	'',	'',	'',	'',	'category-4a'),
(5,	6,	1590836289,	1590836046,	1,	0,	0,	0,	0,	1024,	'',	0,	0,	NULL,	4,	'a:16:{s:5:\"title\";N;s:4:\"slug\";N;s:6:\"parent\";N;s:5:\"items\";N;s:16:\"sys_language_uid\";N;s:6:\"hidden\";N;s:9:\"starttime\";N;s:7:\"endtime\";N;s:9:\"seo_title\";N;s:15:\"seo_description\";N;s:12:\"seo_headline\";N;s:8:\"seo_text\";N;s:6:\"images\";N;s:11:\"description\";N;s:10:\"single_pid\";N;s:8:\"shortcut\";N;}',	0,	0,	0,	0,	0,	0,	0,	'Category 4B',	0,	0,	'0',	0,	0,	0,	'',	'',	'',	'',	'',	'',	'category-4b'),
(6,	6,	1590836299,	1590836046,	1,	0,	0,	0,	0,	768,	'',	0,	0,	NULL,	3,	'a:16:{s:5:\"title\";N;s:4:\"slug\";N;s:6:\"parent\";N;s:5:\"items\";N;s:16:\"sys_language_uid\";N;s:6:\"hidden\";N;s:9:\"starttime\";N;s:7:\"endtime\";N;s:9:\"seo_title\";N;s:15:\"seo_description\";N;s:12:\"seo_headline\";N;s:8:\"seo_text\";N;s:6:\"images\";N;s:11:\"description\";N;s:10:\"single_pid\";N;s:8:\"shortcut\";N;}',	0,	0,	0,	0,	0,	0,	0,	'Category 3B',	0,	0,	'0',	0,	0,	0,	'',	'',	'',	'',	'',	'',	'category-3b'),
(7,	6,	1590836257,	1590836046,	1,	0,	0,	0,	0,	512,	'',	0,	0,	NULL,	2,	'a:16:{s:5:\"title\";N;s:4:\"slug\";N;s:6:\"parent\";N;s:5:\"items\";N;s:16:\"sys_language_uid\";N;s:6:\"hidden\";N;s:9:\"starttime\";N;s:7:\"endtime\";N;s:9:\"seo_title\";N;s:15:\"seo_description\";N;s:12:\"seo_headline\";N;s:8:\"seo_text\";N;s:6:\"images\";N;s:11:\"description\";N;s:10:\"single_pid\";N;s:8:\"shortcut\";N;}',	0,	0,	0,	0,	0,	0,	0,	'Category 2B',	0,	2,	'0',	0,	0,	0,	'',	'',	'',	'',	'',	'',	'category-2b'),
(8,	6,	1590836244,	1590836046,	1,	0,	0,	0,	0,	256,	'',	0,	0,	NULL,	1,	'a:16:{s:5:\"title\";N;s:4:\"slug\";N;s:6:\"parent\";N;s:5:\"items\";N;s:16:\"sys_language_uid\";N;s:6:\"hidden\";N;s:9:\"starttime\";N;s:7:\"endtime\";N;s:9:\"seo_title\";N;s:15:\"seo_description\";N;s:12:\"seo_headline\";N;s:8:\"seo_text\";N;s:6:\"images\";N;s:11:\"description\";N;s:10:\"single_pid\";N;s:8:\"shortcut\";N;}',	0,	0,	0,	0,	0,	0,	0,	'Category 1B',	0,	1,	'0',	0,	0,	0,	'',	'',	'',	'',	'',	'',	'category-1b')
ON DUPLICATE KEY UPDATE `uid` = VALUES(`uid`), `pid` = VALUES(`pid`), `tstamp` = VALUES(`tstamp`), `crdate` = VALUES(`crdate`), `cruser_id` = VALUES(`cruser_id`), `deleted` = VALUES(`deleted`), `hidden` = VALUES(`hidden`), `starttime` = VALUES(`starttime`), `endtime` = VALUES(`endtime`), `sorting` = VALUES(`sorting`), `description` = VALUES(`description`), `sys_language_uid` = VALUES(`sys_language_uid`), `l10n_parent` = VALUES(`l10n_parent`), `l10n_state` = VALUES(`l10n_state`), `t3_origuid` = VALUES(`t3_origuid`), `l10n_diffsource` = VALUES(`l10n_diffsource`), `t3ver_oid` = VALUES(`t3ver_oid`), `t3ver_wsid` = VALUES(`t3ver_wsid`), `t3ver_state` = VALUES(`t3ver_state`), `t3ver_stage` = VALUES(`t3ver_stage`), `t3ver_count` = VALUES(`t3ver_count`), `t3ver_tstamp` = VALUES(`t3ver_tstamp`), `t3ver_move_id` = VALUES(`t3ver_move_id`), `title` = VALUES(`title`), `parent` = VALUES(`parent`), `items` = VALUES(`items`), `fe_group` = VALUES(`fe_group`), `images` = VALUES(`images`), `single_pid` = VALUES(`single_pid`), `shortcut` = VALUES(`shortcut`), `import_id` = VALUES(`import_id`), `import_source` = VALUES(`import_source`), `seo_title` = VALUES(`seo_title`), `seo_description` = VALUES(`seo_description`), `seo_headline` = VALUES(`seo_headline`), `seo_text` = VALUES(`seo_text`), `slug` = VALUES(`slug`);

INSERT INTO `sys_category_record_mm` (`uid_local`, `uid_foreign`, `tablenames`, `fieldname`, `sorting`, `sorting_foreign`) VALUES
(1,	1,	'tx_news_domain_model_news',	'categories',	1,	1),
(2,	1,	'tx_news_domain_model_news',	'categories',	1,	2),
(2,	2,	'tx_news_domain_model_news',	'categories',	2,	1),
(3,	3,	'tx_news_domain_model_news',	'categories',	1,	1),
(4,	3,	'tx_news_domain_model_news',	'categories',	1,	2),
(11,	10,	'tx_news_domain_model_news',	'categories',	0,	1)
ON DUPLICATE KEY UPDATE `uid_local` = VALUES(`uid_local`), `uid_foreign` = VALUES(`uid_foreign`), `tablenames` = VALUES(`tablenames`), `fieldname` = VALUES(`fieldname`), `sorting` = VALUES(`sorting`), `sorting_foreign` = VALUES(`sorting_foreign`);

INSERT INTO `sys_file_storage` (`uid`, `pid`, `tstamp`, `crdate`, `cruser_id`, `deleted`, `description`, `name`, `driver`, `configuration`, `is_default`, `is_browsable`, `is_public`, `is_writable`, `is_online`, `auto_extract_metadata`, `processingfolder`) VALUES
(1,	0,	1590185411,	1590185411,	0,	0,	'This is the local fileadmin/ directory. This storage mount has been created automatically by TYPO3.',	'fileadmin/ (auto-created)',	'Local',	'<?xml version=\"1.0\" encoding=\"utf-8\" standalone=\"yes\" ?>\n<T3FlexForms>\n    <data>\n        <sheet index=\"sDEF\">\n            <language index=\"lDEF\">\n                <field index=\"basePath\">\n                    <value index=\"vDEF\">fileadmin/</value>\n                </field>\n                <field index=\"pathType\">\n                    <value index=\"vDEF\">relative</value>\n                </field>\n                <field index=\"caseSensitive\">\n                    <value index=\"vDEF\">1</value>\n                </field>\n            </language>\n        </sheet>\n    </data>\n</T3FlexForms>',	1,	1,	1,	1,	1,	1,	NULL)
ON DUPLICATE KEY UPDATE `uid` = VALUES(`uid`), `pid` = VALUES(`pid`), `tstamp` = VALUES(`tstamp`), `crdate` = VALUES(`crdate`), `cruser_id` = VALUES(`cruser_id`), `deleted` = VALUES(`deleted`), `description` = VALUES(`description`), `name` = VALUES(`name`), `driver` = VALUES(`driver`), `configuration` = VALUES(`configuration`), `is_default` = VALUES(`is_default`), `is_browsable` = VALUES(`is_browsable`), `is_public` = VALUES(`is_public`), `is_writable` = VALUES(`is_writable`), `is_online` = VALUES(`is_online`), `auto_extract_metadata` = VALUES(`auto_extract_metadata`), `processingfolder` = VALUES(`processingfolder`);

INSERT INTO `sys_file` (`uid`, `pid`, `tstamp`, `last_indexed`, `missing`, `storage`, `type`, `metadata`, `identifier`, `identifier_hash`, `folder_hash`, `extension`, `mime_type`, `name`, `sha1`, `size`, `creation_date`, `modification_date`) VALUES
(1,	0,	1590700944,	0,	0,	1,	'2',	0,	'/user_upload/test1.jpg',	'984f1c74213b29590ed270a4cae8d2cfd422cf12',	'19669f1e02c2f16705ec7587044c66443be70725',	'jpg',	'image/jpeg',	'test1.jpg',	'c7254f44aa10b6f89e328731672eda5082fd4976',	42520,	1590700944,	1590700944)
ON DUPLICATE KEY UPDATE `uid` = VALUES(`uid`), `pid` = VALUES(`pid`), `tstamp` = VALUES(`tstamp`), `last_indexed` = VALUES(`last_indexed`), `missing` = VALUES(`missing`), `storage` = VALUES(`storage`), `type` = VALUES(`type`), `metadata` = VALUES(`metadata`), `identifier` = VALUES(`identifier`), `identifier_hash` = VALUES(`identifier_hash`), `folder_hash` = VALUES(`folder_hash`), `extension` = VALUES(`extension`), `mime_type` = VALUES(`mime_type`), `name` = VALUES(`name`), `sha1` = VALUES(`sha1`), `size` = VALUES(`size`), `creation_date` = VALUES(`creation_date`), `modification_date` = VALUES(`modification_date`);

INSERT INTO `sys_file_reference` (`uid`, `pid`, `tstamp`, `crdate`, `cruser_id`, `deleted`, `hidden`, `sys_language_uid`, `l10n_parent`, `l10n_state`, `l10n_diffsource`, `t3ver_oid`, `t3ver_wsid`, `t3ver_state`, `t3ver_stage`, `t3ver_count`, `t3ver_tstamp`, `t3ver_move_id`, `uid_local`, `uid_foreign`, `tablenames`, `fieldname`, `sorting_foreign`, `table_local`, `title`, `description`, `alternative`, `link`, `crop`, `autoplay`, `showinpreview`) VALUES
(1,	3,	1590836228,	1590700955,	1,	0,	0,	0,	0,	NULL,	'a:1:{s:6:\"hidden\";N;}',	0,	0,	0,	0,	0,	0,	0,	1,	1,	'tx_news_domain_model_news',	'fal_media',	1,	'sys_file',	NULL,	NULL,	NULL,	'',	'{\"default\":{\"cropArea\":{\"x\":0,\"y\":0,\"width\":1,\"height\":1},\"selectedRatio\":\"NaN\",\"focusArea\":null}}',	0,	0),
(2,	3,	1599335757,	1590704324,	1,	0,	0,	0,	0,	NULL,	'a:1:{s:6:\"hidden\";N;}',	0,	0,	0,	0,	0,	0,	0,	1,	2,	'tx_news_domain_model_news',	'fal_media',	1,	'sys_file',	NULL,	NULL,	NULL,	'',	'{\"default\":{\"cropArea\":{\"x\":0,\"y\":0,\"width\":1,\"height\":1},\"selectedRatio\":\"NaN\",\"focusArea\":null}}',	0,	0),
(3,	3,	1599335757,	1590704381,	1,	0,	0,	0,	0,	NULL,	'a:9:{s:13:\"showinpreview\";N;s:11:\"alternative\";N;s:11:\"description\";N;s:4:\"link\";N;s:5:\"title\";N;s:4:\"crop\";N;s:9:\"uid_local\";N;s:6:\"hidden\";N;s:16:\"sys_language_uid\";N;}',	0,	0,	0,	0,	0,	0,	0,	1,	2,	'tx_news_domain_model_news',	'fal_media',	2,	'sys_file',	NULL,	NULL,	NULL,	'',	'{\"default\":{\"cropArea\":{\"x\":0,\"y\":0,\"width\":1,\"height\":1},\"selectedRatio\":\"NaN\",\"focusArea\":null}}',	0,	0),
(4,	3,	1590836196,	1590704857,	1,	0,	0,	0,	0,	NULL,	'a:9:{s:13:\"showinpreview\";N;s:11:\"alternative\";N;s:11:\"description\";N;s:4:\"link\";N;s:5:\"title\";N;s:4:\"crop\";N;s:9:\"uid_local\";N;s:6:\"hidden\";N;s:16:\"sys_language_uid\";N;}',	0,	0,	0,	0,	0,	0,	0,	1,	3,	'tx_news_domain_model_news',	'fal_media',	1,	'sys_file',	NULL,	NULL,	NULL,	'',	'{\"default\":{\"cropArea\":{\"x\":0,\"y\":0,\"width\":1,\"height\":1},\"selectedRatio\":\"NaN\",\"focusArea\":null}}',	0,	0),
(6,	6,	1590836349,	1590836046,	1,	0,	0,	0,	0,	NULL,	'a:1:{s:6:\"hidden\";N;}',	0,	0,	0,	0,	0,	0,	0,	1,	5,	'tx_news_domain_model_news',	'fal_media',	1,	'sys_file',	NULL,	NULL,	NULL,	'',	'{\"default\":{\"cropArea\":{\"x\":0,\"y\":0,\"width\":1,\"height\":1},\"selectedRatio\":\"NaN\",\"focusArea\":null}}',	0,	0),
(7,	6,	1590836334,	1590836046,	1,	0,	0,	0,	0,	NULL,	'a:1:{s:6:\"hidden\";N;}',	0,	0,	0,	0,	0,	0,	0,	1,	6,	'tx_news_domain_model_news',	'fal_media',	1,	'sys_file',	NULL,	NULL,	NULL,	'',	'{\"default\":{\"cropArea\":{\"x\":0,\"y\":0,\"width\":1,\"height\":1},\"selectedRatio\":\"NaN\",\"focusArea\":null}}',	0,	0),
(8,	6,	1590836334,	1590836046,	1,	0,	0,	0,	0,	NULL,	'a:1:{s:6:\"hidden\";N;}',	0,	0,	0,	0,	0,	0,	0,	1,	6,	'tx_news_domain_model_news',	'fal_media',	2,	'sys_file',	NULL,	NULL,	NULL,	'',	'{\"default\":{\"cropArea\":{\"x\":0,\"y\":0,\"width\":1,\"height\":1},\"selectedRatio\":\"NaN\",\"focusArea\":null}}',	0,	0),
(9,	6,	1590836321,	1590836046,	1,	0,	0,	0,	0,	NULL,	'a:1:{s:6:\"hidden\";N;}',	0,	0,	0,	0,	0,	0,	0,	1,	7,	'tx_news_domain_model_news',	'fal_media',	1,	'sys_file',	NULL,	NULL,	NULL,	'',	'{\"default\":{\"cropArea\":{\"x\":0,\"y\":0,\"width\":1,\"height\":1},\"selectedRatio\":\"NaN\",\"focusArea\":null}}',	0,	0)
ON DUPLICATE KEY UPDATE `uid` = VALUES(`uid`), `pid` = VALUES(`pid`), `tstamp` = VALUES(`tstamp`), `crdate` = VALUES(`crdate`), `cruser_id` = VALUES(`cruser_id`), `deleted` = VALUES(`deleted`), `hidden` = VALUES(`hidden`), `sys_language_uid` = VALUES(`sys_language_uid`), `l10n_parent` = VALUES(`l10n_parent`), `l10n_state` = VALUES(`l10n_state`), `l10n_diffsource` = VALUES(`l10n_diffsource`), `t3ver_oid` = VALUES(`t3ver_oid`), `t3ver_wsid` = VALUES(`t3ver_wsid`), `t3ver_state` = VALUES(`t3ver_state`), `t3ver_stage` = VALUES(`t3ver_stage`), `t3ver_count` = VALUES(`t3ver_count`), `t3ver_tstamp` = VALUES(`t3ver_tstamp`), `t3ver_move_id` = VALUES(`t3ver_move_id`), `uid_local` = VALUES(`uid_local`), `uid_foreign` = VALUES(`uid_foreign`), `tablenames` = VALUES(`tablenames`), `fieldname` = VALUES(`fieldname`), `sorting_foreign` = VALUES(`sorting_foreign`), `table_local` = VALUES(`table_local`), `title` = VALUES(`title`), `description` = VALUES(`description`), `alternative` = VALUES(`alternative`), `link` = VALUES(`link`), `crop` = VALUES(`crop`), `autoplay` = VALUES(`autoplay`), `showinpreview` = VALUES(`showinpreview`);

INSERT INTO `sys_registry` (`uid`, `entry_namespace`, `entry_key`, `entry_value`) VALUES
(1,	'installUpdate',	'TYPO3\\CMS\\Form\\Hooks\\FormFileExtensionUpdate',	'i:1;'),
(2,	'installUpdate',	'TYPO3\\CMS\\Install\\Updates\\ExtensionManagerTables',	'i:1;'),
(3,	'installUpdate',	'TYPO3\\CMS\\Install\\Updates\\WizardDoneToRegistry',	'i:1;'),
(4,	'installUpdate',	'TYPO3\\CMS\\Install\\Updates\\StartModuleUpdate',	'i:1;'),
(5,	'installUpdate',	'TYPO3\\CMS\\Install\\Updates\\FrontendUserImageUpdateWizard',	'i:1;'),
(6,	'installUpdate',	'TYPO3\\CMS\\Install\\Updates\\DatabaseRowsUpdateWizard',	'i:1;'),
(7,	'installUpdate',	'TYPO3\\CMS\\Install\\Updates\\CommandLineBackendUserRemovalUpdate',	'i:1;'),
(8,	'installUpdate',	'TYPO3\\CMS\\Install\\Updates\\FillTranslationSourceField',	'i:1;'),
(9,	'installUpdate',	'TYPO3\\CMS\\Install\\Updates\\SectionFrameToFrameClassUpdate',	'i:1;'),
(10,	'installUpdate',	'TYPO3\\CMS\\Install\\Updates\\SplitMenusUpdate',	'i:1;'),
(11,	'installUpdate',	'TYPO3\\CMS\\Install\\Updates\\BulletContentElementUpdate',	'i:1;'),
(12,	'installUpdate',	'TYPO3\\CMS\\Install\\Updates\\UploadContentElementUpdate',	'i:1;'),
(13,	'installUpdate',	'TYPO3\\CMS\\Install\\Updates\\MigrateFscStaticTemplateUpdate',	'i:1;'),
(14,	'installUpdate',	'TYPO3\\CMS\\Install\\Updates\\FileReferenceUpdate',	'i:1;'),
(15,	'installUpdate',	'TYPO3\\CMS\\Install\\Updates\\MigrateFeSessionDataUpdate',	'i:1;'),
(16,	'installUpdate',	'TYPO3\\CMS\\Install\\Updates\\Compatibility7ExtractionUpdate',	'i:1;'),
(17,	'installUpdate',	'TYPO3\\CMS\\Install\\Updates\\FormLegacyExtractionUpdate',	'i:1;'),
(18,	'installUpdate',	'TYPO3\\CMS\\Install\\Updates\\RteHtmlAreaExtractionUpdate',	'i:1;'),
(19,	'installUpdate',	'TYPO3\\CMS\\Install\\Updates\\LanguageSortingUpdate',	'i:1;'),
(20,	'installUpdate',	'TYPO3\\CMS\\Install\\Updates\\Typo3DbExtractionUpdate',	'i:1;'),
(21,	'installUpdate',	'TYPO3\\CMS\\Install\\Updates\\FuncExtractionUpdate',	'i:1;'),
(22,	'installUpdate',	'TYPO3\\CMS\\Install\\Updates\\MigrateUrlTypesInPagesUpdate',	'i:1;'),
(23,	'installUpdate',	'TYPO3\\CMS\\Install\\Updates\\SeparateSysHistoryFromSysLogUpdate',	'i:1;'),
(24,	'installUpdate',	'TYPO3\\CMS\\Install\\Updates\\RedirectExtractionUpdate',	'i:1;'),
(25,	'installUpdate',	'TYPO3\\CMS\\Install\\Updates\\BackendUserStartModuleUpdate',	'i:1;'),
(26,	'installUpdate',	'TYPO3\\CMS\\Install\\Updates\\MigratePagesLanguageOverlayUpdate',	'i:1;'),
(27,	'installUpdate',	'TYPO3\\CMS\\Install\\Updates\\MigratePagesLanguageOverlayBeGroupsAccessRights',	'i:1;'),
(28,	'installUpdate',	'TYPO3\\CMS\\Install\\Updates\\BackendLayoutIconUpdateWizard',	'i:1;'),
(29,	'installUpdate',	'TYPO3\\CMS\\Install\\Updates\\RedirectsExtensionUpdate',	'i:1;'),
(30,	'installUpdate',	'TYPO3\\CMS\\Install\\Updates\\AdminPanelInstall',	'i:1;'),
(31,	'installUpdate',	'TYPO3\\CMS\\Install\\Updates\\PopulatePageSlugs',	'i:1;'),
(32,	'installUpdate',	'TYPO3\\CMS\\Install\\Updates\\Argon2iPasswordHashes',	'i:1;'),
(33,	'installUpdate',	'TYPO3\\CMS\\Install\\Updates\\BackendUserConfigurationUpdate',	'i:1;'),
(34,	'core',	'formProtectionSessionToken:1',	's:64:\"4f27fb163f6e8ddceb8647d30aa4b8e869e365d683256206adbcf0cf68badf1e\";'),
(35,	'tx_reports',	'status.highestSeverity',	'i:2;'),
(36,	'extensionDataImport',	'typo3/sysext/core/ext_tables_static+adt.sql',	's:0:\"\";'),
(37,	'extensionDataImport',	'typo3/sysext/extbase/ext_tables_static+adt.sql',	's:0:\"\";'),
(38,	'extensionDataImport',	'typo3/sysext/fluid/ext_tables_static+adt.sql',	's:0:\"\";'),
(39,	'extensionDataImport',	'typo3/sysext/install/ext_tables_static+adt.sql',	's:0:\"\";'),
(40,	'extensionDataImport',	'typo3/sysext/recordlist/ext_tables_static+adt.sql',	's:0:\"\";'),
(41,	'extensionDataImport',	'typo3/sysext/backend/ext_tables_static+adt.sql',	's:0:\"\";'),
(42,	'extensionDataImport',	'typo3/sysext/setup/ext_tables_static+adt.sql',	's:0:\"\";'),
(43,	'extensionDataImport',	'typo3/sysext/rte_ckeditor/ext_tables_static+adt.sql',	's:0:\"\";'),
(44,	'extensionDataImport',	'typo3/sysext/about/ext_tables_static+adt.sql',	's:0:\"\";'),
(45,	'extensionDataImport',	'typo3/sysext/adminpanel/ext_tables_static+adt.sql',	's:0:\"\";'),
(46,	'extensionDataImport',	'typo3/sysext/belog/ext_tables_static+adt.sql',	's:0:\"\";'),
(47,	'extensionDataImport',	'typo3/sysext/extensionmanager/ext_tables_static+adt.sql',	's:32:\"9beb0be917f14fdde2c9cb940a47d38e\";'),
(48,	'extensionDataImport',	'typo3/sysext/filelist/ext_tables_static+adt.sql',	's:0:\"\";'),
(49,	'extensionDataImport',	'typo3/sysext/frontend/ext_tables_static+adt.sql',	's:0:\"\";'),
(50,	'extensionDataImport',	'typo3/sysext/info/ext_tables_static+adt.sql',	's:0:\"\";'),
(51,	'extensionDataImport',	'typo3/sysext/recycler/ext_tables_static+adt.sql',	's:0:\"\";'),
(52,	'extensionDataImport',	'typo3/sysext/reports/ext_tables_static+adt.sql',	's:0:\"\";'),
(53,	'extensionDataImport',	'typo3/sysext/t3editor/ext_tables_static+adt.sql',	's:0:\"\";'),
(54,	'extensionDataImport',	'typo3/sysext/tstemplate/ext_tables_static+adt.sql',	's:0:\"\";'),
(55,	'extensionDataImport',	'typo3conf/ext/news/ext_tables_static+adt.sql',	's:0:\"\";'),
(56,	'extensionDataImport',	'typo3conf/ext/t3api/ext_tables_static+adt.sql',	's:0:\"\";'),
(57,	'extensionDataImport',	'typo3conf/ext/t3apinews/ext_tables_static+adt.sql',	's:0:\"\";'),
(58,	'installUpdate',	'TYPO3\\CMS\\Install\\Updates\\RsaauthExtractionUpdate',	'i:1;'),
(59,	'installUpdate',	'TYPO3\\CMS\\Install\\Updates\\FeeditExtractionUpdate',	'i:1;'),
(60,	'installUpdate',	'TYPO3\\CMS\\Install\\Updates\\TaskcenterExtractionUpdate',	'i:1;'),
(61,	'installUpdate',	'TYPO3\\CMS\\Install\\Updates\\SysActionExtractionUpdate',	'i:1;'),
(62,	'extensionDataImport',	'typo3conf/ext/t3adminer/ext_tables_static+adt.sql',	's:0:\"\";')
ON DUPLICATE KEY UPDATE `uid` = VALUES(`uid`), `entry_namespace` = VALUES(`entry_namespace`), `entry_key` = VALUES(`entry_key`), `entry_value` = VALUES(`entry_value`);

INSERT INTO `tx_news_domain_model_news` (`uid`, `pid`, `tstamp`, `crdate`, `cruser_id`, `t3ver_oid`, `t3ver_id`, `t3ver_wsid`, `t3ver_label`, `t3ver_state`, `t3ver_stage`, `t3ver_count`, `t3ver_tstamp`, `t3ver_move_id`, `t3_origuid`, `editlock`, `sys_language_uid`, `l10n_parent`, `l10n_diffsource`, `l10n_source`, `deleted`, `hidden`, `starttime`, `endtime`, `fe_group`, `notes`, `l10n_state`, `sorting`, `title`, `teaser`, `bodytext`, `datetime`, `archive`, `author`, `author_email`, `categories`, `related`, `related_from`, `related_files`, `fal_related_files`, `related_links`, `type`, `keywords`, `description`, `tags`, `media`, `fal_media`, `internalurl`, `externalurl`, `istopnews`, `content_elements`, `path_segment`, `alternative_title`, `import_id`, `import_source`, `sitemap_changefreq`, `sitemap_priority`) VALUES
(1,	3,	1590836228,	1590700955,	1,	0,	0,	0,	'',	0,	0,	0,	0,	0,	0,	0,	0,	0,	'a:27:{s:4:\"type\";N;s:9:\"istopnews\";N;s:5:\"title\";N;s:12:\"path_segment\";N;s:6:\"teaser\";N;s:8:\"datetime\";N;s:7:\"archive\";N;s:8:\"bodytext\";N;s:16:\"content_elements\";N;s:9:\"fal_media\";N;s:17:\"fal_related_files\";N;s:10:\"categories\";N;s:7:\"related\";N;s:13:\"related_links\";N;s:4:\"tags\";N;s:6:\"author\";N;s:12:\"author_email\";N;s:8:\"keywords\";N;s:11:\"description\";N;s:17:\"alternative_title\";N;s:16:\"sys_language_uid\";N;s:6:\"hidden\";N;s:9:\"starttime\";N;s:7:\"endtime\";N;s:8:\"fe_group\";N;s:8:\"editlock\";N;s:5:\"notes\";N;}',	0,	0,	0,	0,	0,	'',	'',	NULL,	0,	'Sed ut perspiciatis unde omnis iste natus error sit voluptatem folder A',	'',	'<p>Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p>',	1590693600,	0,	'',	'',	2,	0,	0,	NULL,	0,	'0',	'0',	'',	'',	2,	NULL,	1,	NULL,	NULL,	0,	0,	'sed-ut-perspiciatis-unde-omnis-iste-natus-error-sit-voluptatem-folder-a',	'',	'',	'',	'',	0.5),
(2,	3,	1599335757,	1590704324,	1,	0,	0,	0,	'',	0,	0,	0,	0,	0,	1,	0,	0,	0,	'a:27:{s:4:\"type\";N;s:9:\"istopnews\";N;s:5:\"title\";N;s:12:\"path_segment\";N;s:6:\"teaser\";N;s:8:\"datetime\";N;s:7:\"archive\";N;s:8:\"bodytext\";N;s:16:\"content_elements\";N;s:9:\"fal_media\";N;s:17:\"fal_related_files\";N;s:10:\"categories\";N;s:7:\"related\";N;s:13:\"related_links\";N;s:4:\"tags\";N;s:6:\"author\";N;s:12:\"author_email\";N;s:8:\"keywords\";N;s:11:\"description\";N;s:17:\"alternative_title\";N;s:16:\"sys_language_uid\";N;s:6:\"hidden\";N;s:9:\"starttime\";N;s:7:\"endtime\";N;s:8:\"fe_group\";N;s:8:\"editlock\";N;s:5:\"notes\";N;}',	0,	0,	0,	0,	0,	'',	'',	NULL,	0,	'Natus error sit voluptatem folder A',	'',	'<p>Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas.</p>',	1590695100,	0,	'',	'',	1,	0,	0,	NULL,	0,	'0',	'0',	'',	'',	2,	NULL,	2,	NULL,	NULL,	1,	0,	'natus-error-sit-voluptatem-folder-a',	'',	'',	'',	'',	0.5),
(3,	3,	1590836196,	1590704475,	1,	0,	0,	0,	'',	0,	0,	0,	0,	0,	0,	0,	0,	0,	'a:27:{s:4:\"type\";N;s:9:\"istopnews\";N;s:5:\"title\";N;s:12:\"path_segment\";N;s:6:\"teaser\";N;s:8:\"datetime\";N;s:7:\"archive\";N;s:8:\"bodytext\";N;s:16:\"content_elements\";N;s:9:\"fal_media\";N;s:17:\"fal_related_files\";N;s:10:\"categories\";N;s:7:\"related\";N;s:13:\"related_links\";N;s:4:\"tags\";N;s:6:\"author\";N;s:12:\"author_email\";N;s:8:\"keywords\";N;s:11:\"description\";N;s:17:\"alternative_title\";N;s:16:\"sys_language_uid\";N;s:6:\"hidden\";N;s:9:\"starttime\";N;s:7:\"endtime\";N;s:8:\"fe_group\";N;s:8:\"editlock\";N;s:5:\"notes\";N;}',	0,	0,	0,	0,	0,	'',	'',	NULL,	0,	'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur folder A',	'',	'<p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.</p>',	1590783000,	0,	'',	'',	2,	0,	0,	NULL,	0,	'0',	'0',	'',	'',	1,	NULL,	1,	NULL,	NULL,	0,	0,	'ut-enim-ad-minima-veniam-quis-nostrum-exercitationem-ullam-corporis-suscipit-laboriosam-nisi-ut-aliquid-ex-ea-commodi-consequatur-folder-a',	'',	'',	'',	'',	0.5),
(5,	6,	1590836349,	1590836046,	1,	0,	0,	0,	'',	0,	0,	0,	0,	0,	1,	0,	0,	0,	'a:27:{s:4:\"type\";N;s:9:\"istopnews\";N;s:5:\"title\";N;s:12:\"path_segment\";N;s:6:\"teaser\";N;s:8:\"datetime\";N;s:7:\"archive\";N;s:8:\"bodytext\";N;s:16:\"content_elements\";N;s:9:\"fal_media\";N;s:17:\"fal_related_files\";N;s:10:\"categories\";N;s:7:\"related\";N;s:13:\"related_links\";N;s:4:\"tags\";N;s:6:\"author\";N;s:12:\"author_email\";N;s:8:\"keywords\";N;s:11:\"description\";N;s:17:\"alternative_title\";N;s:16:\"sys_language_uid\";N;s:6:\"hidden\";N;s:9:\"starttime\";N;s:7:\"endtime\";N;s:8:\"fe_group\";N;s:8:\"editlock\";N;s:5:\"notes\";N;}',	0,	0,	0,	0,	0,	'',	'',	NULL,	0,	'Sed ut perspiciatis unde omnis iste natus error sit voluptatem folder B',	'',	'<p>Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p>',	1590693600,	0,	'',	'',	0,	0,	0,	NULL,	0,	'0',	'0',	'',	'',	2,	NULL,	1,	NULL,	NULL,	0,	0,	'sed-ut-perspiciatis-unde-omnis-iste-natus-error-sit-voluptatem-folder-b',	'',	'',	'',	'',	0.5),
(6,	6,	1590836334,	1590836046,	1,	0,	0,	0,	'',	0,	0,	0,	0,	0,	2,	0,	0,	0,	'a:27:{s:4:\"type\";N;s:9:\"istopnews\";N;s:5:\"title\";N;s:12:\"path_segment\";N;s:6:\"teaser\";N;s:8:\"datetime\";N;s:7:\"archive\";N;s:8:\"bodytext\";N;s:16:\"content_elements\";N;s:9:\"fal_media\";N;s:17:\"fal_related_files\";N;s:10:\"categories\";N;s:7:\"related\";N;s:13:\"related_links\";N;s:4:\"tags\";N;s:6:\"author\";N;s:12:\"author_email\";N;s:8:\"keywords\";N;s:11:\"description\";N;s:17:\"alternative_title\";N;s:16:\"sys_language_uid\";N;s:6:\"hidden\";N;s:9:\"starttime\";N;s:7:\"endtime\";N;s:8:\"fe_group\";N;s:8:\"editlock\";N;s:5:\"notes\";N;}',	0,	0,	0,	0,	0,	'',	'',	NULL,	0,	'Natus error sit voluptatem folder B',	'',	'<p>Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas.</p>',	1590695100,	0,	'',	'',	0,	0,	0,	NULL,	0,	'0',	'0',	'',	'',	2,	NULL,	2,	NULL,	NULL,	0,	0,	'natus-error-sit-voluptatem-folder-b',	'',	'',	'',	'',	0.5),
(7,	6,	1590836321,	1590836046,	1,	0,	0,	0,	'',	0,	0,	0,	0,	0,	3,	0,	0,	0,	'a:27:{s:4:\"type\";N;s:9:\"istopnews\";N;s:5:\"title\";N;s:12:\"path_segment\";N;s:6:\"teaser\";N;s:8:\"datetime\";N;s:7:\"archive\";N;s:8:\"bodytext\";N;s:16:\"content_elements\";N;s:9:\"fal_media\";N;s:17:\"fal_related_files\";N;s:10:\"categories\";N;s:7:\"related\";N;s:13:\"related_links\";N;s:4:\"tags\";N;s:6:\"author\";N;s:12:\"author_email\";N;s:8:\"keywords\";N;s:11:\"description\";N;s:17:\"alternative_title\";N;s:16:\"sys_language_uid\";N;s:6:\"hidden\";N;s:9:\"starttime\";N;s:7:\"endtime\";N;s:8:\"fe_group\";N;s:8:\"editlock\";N;s:5:\"notes\";N;}',	0,	0,	0,	0,	0,	'',	'',	NULL,	0,	'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur folder B',	'',	'<p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.</p>',	1590783000,	0,	'',	'',	0,	0,	0,	NULL,	0,	'0',	'0',	'',	'',	1,	NULL,	1,	NULL,	NULL,	0,	0,	'ut-enim-ad-minima-veniam-quis-nostrum-exercitationem-ullam-corporis-suscipit-laboriosam-nisi-ut-aliquid-ex-ea-commodi-consequatur-folder-b',	'',	'',	'',	'',	0.5)
ON DUPLICATE KEY UPDATE `uid` = VALUES(`uid`), `pid` = VALUES(`pid`), `tstamp` = VALUES(`tstamp`), `crdate` = VALUES(`crdate`), `cruser_id` = VALUES(`cruser_id`), `t3ver_oid` = VALUES(`t3ver_oid`), `t3ver_id` = VALUES(`t3ver_id`), `t3ver_wsid` = VALUES(`t3ver_wsid`), `t3ver_label` = VALUES(`t3ver_label`), `t3ver_state` = VALUES(`t3ver_state`), `t3ver_stage` = VALUES(`t3ver_stage`), `t3ver_count` = VALUES(`t3ver_count`), `t3ver_tstamp` = VALUES(`t3ver_tstamp`), `t3ver_move_id` = VALUES(`t3ver_move_id`), `t3_origuid` = VALUES(`t3_origuid`), `editlock` = VALUES(`editlock`), `sys_language_uid` = VALUES(`sys_language_uid`), `l10n_parent` = VALUES(`l10n_parent`), `l10n_diffsource` = VALUES(`l10n_diffsource`), `l10n_source` = VALUES(`l10n_source`), `deleted` = VALUES(`deleted`), `hidden` = VALUES(`hidden`), `starttime` = VALUES(`starttime`), `endtime` = VALUES(`endtime`), `fe_group` = VALUES(`fe_group`), `notes` = VALUES(`notes`), `l10n_state` = VALUES(`l10n_state`), `sorting` = VALUES(`sorting`), `title` = VALUES(`title`), `teaser` = VALUES(`teaser`), `bodytext` = VALUES(`bodytext`), `datetime` = VALUES(`datetime`), `archive` = VALUES(`archive`), `author` = VALUES(`author`), `author_email` = VALUES(`author_email`), `categories` = VALUES(`categories`), `related` = VALUES(`related`), `related_from` = VALUES(`related_from`), `related_files` = VALUES(`related_files`), `fal_related_files` = VALUES(`fal_related_files`), `related_links` = VALUES(`related_links`), `type` = VALUES(`type`), `keywords` = VALUES(`keywords`), `description` = VALUES(`description`), `tags` = VALUES(`tags`), `media` = VALUES(`media`), `fal_media` = VALUES(`fal_media`), `internalurl` = VALUES(`internalurl`), `externalurl` = VALUES(`externalurl`), `istopnews` = VALUES(`istopnews`), `content_elements` = VALUES(`content_elements`), `path_segment` = VALUES(`path_segment`), `alternative_title` = VALUES(`alternative_title`), `import_id` = VALUES(`import_id`), `import_source` = VALUES(`import_source`), `sitemap_changefreq` = VALUES(`sitemap_changefreq`), `sitemap_priority` = VALUES(`sitemap_priority`);

INSERT INTO `tx_news_domain_model_news_tag_mm` (`uid_local`, `uid_foreign`, `sorting`) VALUES
(1,	1,	1),
(1,	4,	2),
(2,	1,	1),
(2,	2,	2),
(3,	4,	1),
(4,	4,	1),
(5,	6,	1),
(5,	9,	2),
(6,	6,	1),
(6,	7,	2),
(7,	9,	1)
ON DUPLICATE KEY UPDATE `uid_local` = VALUES(`uid_local`), `uid_foreign` = VALUES(`uid_foreign`), `sorting` = VALUES(`sorting`);


INSERT INTO `tx_news_domain_model_tag` (`uid`, `pid`, `tstamp`, `crdate`, `cruser_id`, `deleted`, `hidden`, `sys_language_uid`, `l10n_parent`, `l10n_diffsource`, `l10n_source`, `notes`, `l10n_state`, `sorting`, `t3ver_oid`, `t3ver_id`, `t3_origuid`, `t3ver_wsid`, `t3ver_label`, `t3ver_state`, `t3ver_stage`, `t3ver_count`, `t3ver_tstamp`, `t3ver_move_id`, `title`, `slug`, `seo_title`, `seo_description`, `seo_headline`, `seo_text`) VALUES
(1,	3,	1590701033,	1590701033,	1,	0,	0,	0,	0,	'',	0,	'',	NULL,	0,	0,	0,	0,	0,	'',	0,	0,	0,	0,	0,	'Tag 1',	'tag-1',	'',	'',	'',	''),
(2,	3,	1590701041,	1590701041,	1,	0,	0,	0,	0,	'',	0,	'',	NULL,	0,	0,	0,	0,	0,	'',	0,	0,	0,	0,	0,	'Tag 2',	'tag-2',	'',	'',	'',	''),
(3,	3,	1590701064,	1590701048,	1,	0,	0,	0,	0,	'a:9:{s:5:\"title\";N;s:4:\"slug\";N;s:6:\"hidden\";N;s:9:\"seo_title\";N;s:15:\"seo_description\";N;s:12:\"seo_headline\";N;s:8:\"seo_text\";N;s:5:\"notes\";N;s:16:\"sys_language_uid\";N;}',	0,	'',	NULL,	0,	0,	0,	0,	0,	'',	0,	0,	0,	0,	0,	'Tag 3',	'tag-3',	'',	'',	'',	''),
(4,	3,	1590701072,	1590701072,	1,	0,	0,	0,	0,	'',	0,	'',	NULL,	0,	0,	0,	0,	0,	'',	0,	0,	0,	0,	0,	'Tag 4',	'tag-4',	'',	'',	'',	''),
(6,	6,	1590836046,	1590836046,	1,	0,	0,	0,	0,	'',	0,	'',	NULL,	0,	0,	0,	0,	0,	'',	0,	0,	0,	0,	0,	'Tag 10',	'tag-1-1',	'',	'',	'',	''),
(7,	6,	1590836046,	1590836046,	1,	0,	0,	0,	0,	'',	0,	'',	NULL,	0,	0,	0,	0,	0,	'',	0,	0,	0,	0,	0,	'Tag 20',	'tag-2-1',	'',	'',	'',	''),
(8,	6,	1590836046,	1590836046,	1,	0,	0,	0,	0,	'a:9:{s:5:\"title\";N;s:4:\"slug\";N;s:6:\"hidden\";N;s:9:\"seo_title\";N;s:15:\"seo_description\";N;s:12:\"seo_headline\";N;s:8:\"seo_text\";N;s:5:\"notes\";N;s:16:\"sys_language_uid\";N;}',	0,	'',	NULL,	0,	0,	0,	0,	0,	'',	0,	0,	0,	0,	0,	'Tag 30',	'tag-3-1',	'',	'',	'',	''),
(9,	6,	1590836046,	1590836046,	1,	0,	0,	0,	0,	'',	0,	'',	NULL,	0,	0,	0,	0,	0,	'',	0,	0,	0,	0,	0,	'Tag 40',	'tag-4-1',	'',	'',	'',	'')
ON DUPLICATE KEY UPDATE `uid` = VALUES(`uid`), `pid` = VALUES(`pid`), `tstamp` = VALUES(`tstamp`), `crdate` = VALUES(`crdate`), `cruser_id` = VALUES(`cruser_id`), `deleted` = VALUES(`deleted`), `hidden` = VALUES(`hidden`), `sys_language_uid` = VALUES(`sys_language_uid`), `l10n_parent` = VALUES(`l10n_parent`), `l10n_diffsource` = VALUES(`l10n_diffsource`), `l10n_source` = VALUES(`l10n_source`), `notes` = VALUES(`notes`), `l10n_state` = VALUES(`l10n_state`), `sorting` = VALUES(`sorting`), `t3ver_oid` = VALUES(`t3ver_oid`), `t3ver_id` = VALUES(`t3ver_id`), `t3_origuid` = VALUES(`t3_origuid`), `t3ver_wsid` = VALUES(`t3ver_wsid`), `t3ver_label` = VALUES(`t3ver_label`), `t3ver_state` = VALUES(`t3ver_state`), `t3ver_stage` = VALUES(`t3ver_stage`), `t3ver_count` = VALUES(`t3ver_count`), `t3ver_tstamp` = VALUES(`t3ver_tstamp`), `t3ver_move_id` = VALUES(`t3ver_move_id`), `title` = VALUES(`title`), `slug` = VALUES(`slug`), `seo_title` = VALUES(`seo_title`), `seo_description` = VALUES(`seo_description`), `seo_headline` = VALUES(`seo_headline`), `seo_text` = VALUES(`seo_text`);

-- 2020-11-13 18:37:14
