#!/bin/bash

## Description: [ExtDev] Import/export data and files for extension development.
## Usage: data
## Example: "ddev data import 12", "ddev data export 12"

source .ddev/test/utils.sh

importData() {
    mysql -uroot -proot -Nse 'SHOW TABLES' "${DATABASE}" | while read -r table; do
        mysql -uroot -proot -e "SET FOREIGN_KEY_CHECKS = 0; DROP TABLE IF EXISTS ${table}" "${DATABASE}";
    done
    ${TYPO3_CLI} database:updateschema

    if [ -d "${EXPORT_DIR:?}" ]; then
        find "${EXPORT_DIR}" -mindepth 1 -delete
    else
        echo "Error: EXPORT_DIR is not set or points to a non-existent directory."
        exit 1
    fi
    cp -r "${TEST_SRC_IMPEXP_DIR}"/* "${EXPORT_DIR}/"
    ${TYPO3_CLI} impexp:import -vvv --force-uid "${EXPORT_DIR}/${EXPORT_FILE}"
}

exportData() {
    BASE_DIR="${PUBLIC_DIR}/fileadmin"
    find "${BASE_DIR}" -type f -name "*index.html" -exec rm -f {} +
    find "${BASE_DIR}/user_upload/_temp_/" -type f -exec rm -f {} +
    find "${BASE_DIR}/user_upload/${MEDIA_EXPORT_EXCLUDED}/" -type f -exec rm -f {} +
    mysql -uroot -proot "${DATABASE}" -e "DELETE FROM sys_file WHERE identifier LIKE '/user_upload/_temp_/%' OR identifier LIKE '%index.html' OR identifier LIKE '/user_upload/${MEDIA_EXPORT_EXCLUDED}/%';"
    mysql -uroot -proot "${DATABASE}" -e "DELETE sys_file_metadata FROM sys_file_metadata LEFT JOIN sys_file ON sys_file_metadata.file = sys_file.uid WHERE sys_file.uid IS NULL OR sys_file.identifier LIKE '/user_upload/_temp_/%' OR sys_file.identifier LIKE '%index.html' OR identifier LIKE '/user_upload/${MEDIA_EXPORT_EXCLUDED}/%';"
    mysql -uroot -proot "${DATABASE}" -e "DELETE sys_file_reference FROM sys_file_reference LEFT JOIN sys_file ON sys_file_reference.uid_local = sys_file.uid WHERE sys_file.uid IS NULL;"
    mysql -uroot -proot "${DATABASE}" -e "TRUNCATE be_sessions; TRUNCATE fe_sessions; TRUNCATE sys_file_processedfile; TRUNCATE sys_lockedrecords; TRUNCATE tx_extensionmanager_domain_model_extension;"

    ${TYPO3_CLI} cleanup:missingrelations --update-refindex
    ${TYPO3_CLI} cleanup:flexforms
    ${TYPO3_CLI} cleanup:deletedrecords
    ${TYPO3_CLI} cleanup:orphanrecords
    ${TYPO3_CLI} cache:flush

    mysql -uroot -proot "${DATABASE}" -e "TRUNCATE sys_history; TRUNCATE sys_log;"

    ${TYPO3_CLI} impexp:export    -vvv \
                                --type=xml \
                                --pid=0 \
                                --levels=999 \
                                --table=_ALL \
                                --include-related=_ALL \
                                --include-static=_ALL \
                                --save-files-outside-export-file \
                                "${EXPORT_NAME}"

    # Hardcode some not important values to make the diff smaller
    sed -i 's|<field index="tstamp" type="integer">[^<]*</field>|<field index="tstamp" type="integer">1717269219</field>|g' "${EXPORT_PATH}"
    sed -i 's|<field index="crdate" type="integer">[^<]*</field>|<field index="crdate" type="integer">1717269219</field>|g' "${EXPORT_PATH}"
    sed -i 's|<field index="creation_date" type="integer">[^<]*</field>|<field index="creation_date" type="integer">1717269219</field>|g' "${EXPORT_PATH}"
    sed -i 's|<field index="last_indexed" type="integer">[^<]*</field>|<field index="last_indexed" type="integer">1717269219</field>|g' "${EXPORT_PATH}"
    sed -i 's|<field index="SYS_LASTCHANGED" type="integer">[^<]*</field>|<field index="SYS_LASTCHANGED" type="integer">1717269219</field>|g' "${EXPORT_PATH}"
    sed -i 's|<field index="modification_date" type="integer">[^<]*</field>|<field index="modification_date" type="integer">1717269219</field>|g' "${EXPORT_PATH}"
    sed -i 's|<field index="perms_userid" type="integer">[^<]*</field>|<field index="perms_userid" type="integer">2</field>|g' "${EXPORT_PATH}"
    sed -i 's|<filemtime>[^<]*</filemtime>|<filemtime>1717269219</filemtime>|g' "${EXPORT_PATH}"
    sed -i 's|<created>[^<]*</created>|<created>Sat 22. April 2024</created>|g' "${EXPORT_PATH}"

    if [ -z "${TEST_SRC_IMPEXP_DIR}" ]; then
        echo "Error: TEST_SRC_IMPEXP_DIR is not set or empty."
        exit 1
    fi
    xml_file_count=$(find "${TEST_SRC_IMPEXP_DIR}" -maxdepth 1 -type f -name "*.xml" | wc -l)
    if [ "${xml_file_count}" -ne 1 ]; then
        echo "Error: There must be exactly one XML file in ${TEST_SRC_IMPEXP_DIR}."
        exit 1
    fi
    xml_file_name=$(basename "$(find "${TEST_SRC_IMPEXP_DIR}" -maxdepth 1 -type f -name "*.xml")")
    rm -f "${TEST_SRC_IMPEXP_DIR}/${xml_file_name}"
    rm -rf "${TEST_SRC_IMPEXP_DIR}/${xml_file_name}.files"

    mkdir -p "${TEST_SRC_IMPEXP_DIR}"
    mv "${EXPORT_PATH}" "${TEST_SRC_IMPEXP_DIR}"
    mv "${EXPORT_PATH}.files/" "${TEST_SRC_IMPEXP_DIR}"

    message green "Dump finished and saved at ${TEST_SRC_IMPEXP_DIR}/${EXPORT_FILE}"
}


if [ -z "${DDEV_COMPOSER_ROOT}" ]; then
    echo "Error: DDEV_COMPOSER_ROOT is not set or empty."
    exit 1
fi

OPERATION_TYPE=${1}
TYPO3=${2}
if ! check_typo3_version "${TYPO3}"; then
    exit 1
fi

PROJECT_DIR=${DDEV_COMPOSER_ROOT:-/var/www/html}
PUBLIC_DIR="${PROJECT_DIR}/.test/${TYPO3}/public"
EXPORT_DIR="${PUBLIC_DIR}/fileadmin/user_upload/_temp_/importexport"
EXPORT_NAME="data"
EXPORT_FILE="data.xml"
EXPORT_PATH="${EXPORT_DIR}/${EXPORT_FILE}"
TYPO3_CLI="${PROJECT_DIR}/.test/${TYPO3}/vendor/bin/typo3"
DATABASE="database_${TYPO3}"
TEST_SRC_IMPEXP_DIR="${PROJECT_DIR}/.ddev/test/impexp"
MEDIA_EXPORT_EXCLUDED="${TYPO3_EXTDEV_MEDIA_EXPORT_EXCLUDED:-media-export-excluded}"

if [ "${OPERATION_TYPE}" == "export" ]; then
    exportData
elif [ "${OPERATION_TYPE}" == "import" ]; then
    importData
else
    echo "Invalid operation type. Please use 'export' or 'import'."
    exit 1
fi
