#!/bin/bash

## Description: Dump database to data-init folder.
## Usage: dbdump v12
## Example: "ddev dbdump v12"

if [[ ${@} = "" ]]; then echo "Set v12 as argument." && exit 1; fi

VERSION=$@
DATABASE=database_$VERSION

echo 'TRUNCATE sys_history; TRUNCATE sys_log; TRUNCATE be_sessions; TRUNCATE fe_sessions; TRUNCATE fe_sessions; TRUNCATE sys_file_processedfile; TRUNCATE sys_lockedrecords; TRUNCATE tx_extensionmanager_domain_model_extension;' | mysql -uroot -proot $DATABASE
echo "SELECT concat('TRUNCATE TABLE ', TABLE_NAME, ';') FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = '$DATABASE' AND TABLE_NAME LIKE 'cache%'" | mysql -uroot -proot $DATABASE | sed 1d > tmp.sql
cat tmp.sql | mysql -uroot -proot $DATABASE
rm tmp.sql

mysqldump --skip-triggers --extended-insert --single-transaction --skip-add-locks --skip-disable-keys --quick --skip-comments -uroot -proot -hdb $DATABASE > /var/www/html/.ddev/data-init/$VERSION/database.sql
echo "Dump finished"
