#!/bin/bash

## Description: Install all defined TYPO3 testing instances.
## Usage: install-all
## Example: "ddev install-all"

source .ddev/test/utils.sh

mapfile -t versions < <(get_supported_typo3_versions)

for version in "${versions[@]}"; do
    echo_green "Installing TYPO3 v${version}..."
    .ddev/commands/web/install-$version
done
