#!/bin/bash

## Description: Install all defined TYPO3 testing instances for t3api.
## Usage: install-all
## Example: "ddev install-all"

ABSOLUTE_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}/.")"

$ABSOLUTE_PATH/install-v12
