#!/bin/bash

VERSION=v11
DATABASE=database_${VERSION}

rm -rf /var/www/html/$VERSION/*
mysql -uroot -proot -e "DROP DATABASE IF EXISTS $DATABASE"


cd /var/www/html/$VERSION

composer init --name=sourcebroker/typo3$VERSION --description=TYPO3$VERSION -n -d /var/www/html/$VERSION
composer config extra.typo3/cms.web-dir public -d /var/www/html/$VERSION
composer config repositories.$EXTENSION_KEY path ../$EXTENSION_KEY -d /var/www/html/$VERSION
# Remove when TYPO3 11.5.1 is installed - start
cp -r "/var/www/html/$EXTENSION_KEY/.ddev/data-init/typo3_core_composer_fix.diff" "/var/www/html/$VERSION/"
composer config --json extra.patches.typo3/cms-core '{"[BUGFIX] Populate composer name to extension key map early": "/var/www/html/v11/typo3_core_composer_fix.diff"}'
composer req cweagans/composer-patches:'dev-master'
# Remove when TYPO3 11.5.1 is installed - end
composer req typo3/minimal:'^11.5' typo3/cms-extensionmanager:'^11.5' helhum/typo3-console:'^7.0' georgringer/news:'dev-master as 8.6.0' sourcebroker/t3api:'dev-typo3-115-support' sourcebroker/t3apinews:'dev-typo3-115-support' --no-progress -n -d /var/www/html/$VERSION

vendor/bin/typo3cms install:setup -n --database-name $DATABASE
vendor/bin/typo3cms configuration:set 'BE/debug' 1
vendor/bin/typo3cms configuration:set 'BE/lockSSL' true
vendor/bin/typo3cms configuration:set 'FE/debug' 1
vendor/bin/typo3cms configuration:set 'SYS/devIPmask' '*'
vendor/bin/typo3cms configuration:set 'SYS/displayErrors' 1
vendor/bin/typo3cms configuration:set 'SYS/trustedHostsPattern' '.*.*'
vendor/bin/typo3cms configuration:set 'MAIL/transport' 'smtp'
vendor/bin/typo3cms configuration:set 'MAIL/transport_smtp_server' 'localhost:1025'
vendor/bin/typo3cms configuration:set 'GFX/processor' 'ImageMagick'
vendor/bin/typo3cms configuration:set 'GFX/processor_path' '/usr/bin/'
vendor/bin/typo3cms configuration:set 'GFX/processor_path_lzw' '/usr/bin/'

sed -i -e "s/base: ht\//base: \//g" /var/www/html/$VERSION/config/sites/main/config.yaml
sed -i -e 's/base: \/en\//base: \//g' /var/www/html/$VERSION/config/sites/main/config.yaml
printf "imports:\n  -\n    resource: 'EXT:$EXTENSION_KEY/Configuration/Routing/config.yaml'" >> /var/www/html/$VERSION/config/sites/main/config.yaml

cp -r "/var/www/html/$EXTENSION_KEY/.ddev/data-init/fileadmin/" "/var/www/html/$VERSION/public/"
mysql -uroot -proot  $DATABASE < "/var/www/html/$EXTENSION_KEY/.ddev/data-init/$DATABASE.sql"

vendor/bin/typo3cms database:updateschema
vendor/bin/typo3cms cache:flush
