#!/bin/bash

## Description: Install TYPO3 10 with t3api linked to it.
## Usage: install-v10
## Example: "ddev install-v10"

VERSION=v10
DATABASE=database_$VERSION
BASE_PATH=/var/www/html/.test/$VERSION

[ -L /var/www/html/.test/t3api ] || ln -sr /var/www/html/ /var/www/html/.test/t3api
rm -rf $BASE_PATH
mkdir -p $BASE_PATH

mysql -uroot -proot -e "DROP DATABASE IF EXISTS $DATABASE"

composer init --name=sourcebroker/typo3$VERSION --description=TYPO3$VERSION --no-interaction --working-dir $BASE_PATH
composer config extra.typo3/cms.web-dir public --working-dir $BASE_PATH
composer config repositories.$EXTENSION_KEY path ../$EXTENSION_KEY --working-dir $BASE_PATH
composer config --no-plugins allow-plugins.typo3/cms-composer-installers true --working-dir $BASE_PATH
composer config --no-plugins allow-plugins.typo3/class-alias-loader true --working-dir $BASE_PATH
composer req typo3/minimal:'^10.4' helhum/typo3-console:'^6.3' jigal/t3adminer:'^9.4' georgringer/news:'^8.0' \
         sourcebroker/t3api:'@dev' sourcebroker/t3apinews:'@dev' \
         --no-progress --no-interaction --working-dir $BASE_PATH

$BASE_PATH/vendor/bin/typo3cms install:setup -n --database-name $DATABASE
$BASE_PATH/vendor/bin/typo3cms configuration:set 'BE/debug' 1
$BASE_PATH/vendor/bin/typo3cms configuration:set 'BE/lockSSL' true
$BASE_PATH/vendor/bin/typo3cms configuration:set 'FE/debug' 1
$BASE_PATH/vendor/bin/typo3cms configuration:set 'SYS/devIPmask' '*'
$BASE_PATH/vendor/bin/typo3cms configuration:set 'SYS/displayErrors' 1
$BASE_PATH/vendor/bin/typo3cms configuration:set 'SYS/trustedHostsPattern' '.*.*'
$BASE_PATH/vendor/bin/typo3cms configuration:set 'MAIL/transport' 'smtp'
$BASE_PATH/vendor/bin/typo3cms configuration:set 'MAIL/transport_smtp_server' 'localhost:1025'
$BASE_PATH/vendor/bin/typo3cms configuration:set 'GFX/processor' 'ImageMagick'
$BASE_PATH/vendor/bin/typo3cms configuration:set 'GFX/processor_path' '/usr/bin/'
$BASE_PATH/vendor/bin/typo3cms configuration:set 'GFX/processor_path_lzw' '/usr/bin/'
$BASE_PATH/vendor/bin/typo3cms install:generatepackagestates

sed -i -e "s/base: ht\//base: \//g" $BASE_PATH/config/sites/main/config.yaml
sed -i -e 's/base: \/en\//base: \//g' $BASE_PATH/config/sites/main/config.yaml
printf "imports:\n  -\n    resource: 'EXT:$EXTENSION_KEY/Configuration/Routing/config.yaml'" >> $BASE_PATH/config/sites/main/config.yaml

cp -r "$BASE_PATH/../$EXTENSION_KEY/.ddev/data-init/fileadmin/" "$BASE_PATH/public/"
mysql -uroot -proot  $DATABASE < "$BASE_PATH/../$EXTENSION_KEY/.ddev/data-init/$DATABASE.sql"

$BASE_PATH/vendor/bin/typo3cms database:updateschema
$BASE_PATH/vendor/bin/typo3cms cache:flush
