#!/bin/bash

## Description: Install TYPO3 12 with t3api linked to it.
## Usage: install-v12
## Example: "ddev install-v12"

set +x

VERSION=v12
BASE_PATH=/var/www/html/.test/$VERSION
TYPO3_BIN=$BASE_PATH/vendor/bin/typo3
DATABASE=database_$VERSION

rm -rf $BASE_PATH

exclusions=(".*" "Documentation" "Documentation-GENERATED-temp" "var")
mkdir -p "$BASE_PATH/src/$EXTENSION_KEY"
for item in /var/www/html/*; do
    base_name=$(basename "$item")
    for exclusion in "${exclusions[@]}"; do
        if [[ $base_name == "$exclusion" ]]; then
            continue 2
        fi
    done
    ln -sr "$item" "$BASE_PATH/src/$EXTENSION_KEY/$base_name"
done

mysql -uroot -proot -e "DROP DATABASE IF EXISTS $DATABASE"

composer init --name=sourcebroker/typo3$VERSION --description=TYPO3$VERSION --no-interaction --working-dir $BASE_PATH
composer config extra.typo3/cms.web-dir public --working-dir $BASE_PATH
composer config repositories.src path 'src/*' --working-dir $BASE_PATH
composer config --no-interaction allow-plugins.typo3/cms-composer-installers true --working-dir $BASE_PATH
composer config --no-interaction allow-plugins.typo3/class-alias-loader true --working-dir $BASE_PATH
composer req typo3/minimal:'^12.4' typo3/cms-recycler:'^12.4' typo3/cms-tstemplate:'^12.4' typo3/cms-info:'^12.4' \
         typo3/cms-lowlevel:'^12.4' typo3/cms-rte-ckeditor:'^12.4' \
         helhum/typo3-console:'^8.1' georgringer/news:'^11.3.0' \
         sourcebroker/t3api:'@dev' sourcebroker/t3apinews:'v12.x-dev' \
         --no-progress --no-interaction --working-dir $BASE_PATH

$TYPO3_BIN install:setup -n --database-name $DATABASE
$TYPO3_BIN configuration:set 'BE/debug' 1
$TYPO3_BIN configuration:set 'BE/lockSSL' true
$TYPO3_BIN configuration:set 'FE/debug' 1
$TYPO3_BIN configuration:set 'SYS/devIPmask' '*'
$TYPO3_BIN configuration:set 'SYS/displayErrors' 1
$TYPO3_BIN configuration:set 'SYS/trustedHostsPattern' '.*.*'
$TYPO3_BIN configuration:set 'MAIL/transport' 'smtp'
$TYPO3_BIN configuration:set 'MAIL/transport_smtp_server' 'localhost:1025'
$TYPO3_BIN configuration:set 'GFX/processor' 'ImageMagick'
$TYPO3_BIN configuration:set 'GFX/processor_path' '/usr/bin/'

ln -sr ".ddev/data-init/$VERSION/files/src/site/" $BASE_PATH/src/site
rm -rf $BASE_PATH/public/fileadmin/user_upload && ln -srf ".ddev/data-init/$VERSION/files/public/fileadmin/user_upload/" $BASE_PATH/public/fileadmin/user_upload
ln -srf ".ddev/data-init/$VERSION/files/config/sites/main/config.yaml" $BASE_PATH/config/sites/main/config.yaml

mysql -uroot -proot $DATABASE < ".ddev/data-init/$VERSION/database.sql"

composer req v/site:'^1.0.0' --working-dir $BASE_PATH

$TYPO3_BIN database:updateschema
$TYPO3_BIN cache:flush
