#!/bin/bash

## Description: [ExtDev] Tag new extension version.
## Usage: next
## Example: "ddev next, ddev next patch, ddev next minor, ddev next major"

INCREASE_PATCH="patch"
INCREASE_MINOR="minor"
INCREASE_MAJOR="major"

versionType=${1:-$INCREASE_PATCH}

IFS='.' read -ra lastTagParts <<< "$(git tag -l --sort=v:refname | tail -1)"
major=${lastTagParts[0]}
minor=${lastTagParts[1]}
patch=${lastTagParts[2]}

case $versionType in
    $INCREASE_MINOR)
        patch=0
        minor=$((minor+1))
        ;;
    $INCREASE_MAJOR)
        patch=0
        minor=0
        major=$((major+1))
        ;;
    $INCREASE_PATCH)
        patch=$((patch+1))
        ;;
esac

nextTag="$major.$minor.$patch"

sed -i "s/'version' => '[0-9]\+\.[0-9]\+\.[0-9]\+'/'version' => '$nextTag'/g" ./ext_emconf.php

sed -i "s/release=\"[0-9]\+\.[0-9]\+\.[0-9]\+\"/release=\"$nextTag\"/g" ./Documentation/guides.xml
sed -i'' -E "s/(<project[^>]* version=\")[^\"]+(\")/\1$nextTag\2/" ./Documentation/guides.xml

default_branch=$(git remote show origin | grep 'HEAD branch' | cut -d' ' -f5)
echo "git add Documentation/guides.xml ext_emconf.php && git commit -m 'Tag new version' && git tag -a '$nextTag' -m '$nextTag' -s && git push origin $default_branch --tags"
