name: TYPO3 12

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        typo3: ["12"]
        php: ["8.1", "8.2", "8.3"]
        composer: ["lowest", "highest"]
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        uses: ddev/github-action-setup-ddev@v1
      - run: ddev ci ${{ matrix.typo3 }} ${{ matrix.php }} ${{ matrix.composer }}
