name: TYPO3 12

on:
  push:
    branches:
      - main
      - release/4.0.0
  pull_request:
    branches:
      - main
      - release/4.0.0

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        typo3: ["12"]
        php: ["8.1", "8.2", "8.3"]
        composer: ["lowest", "highest"]
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        uses: ddev/github-action-setup-ddev@v1
      - run: |
          if [ -n "$GH_TOKEN" ] && ! ddev composer config --global --list | grep -q "github-oauth.github.com"; then
            echo "Add composer github-oauth.github.com to ddev web container."
            ddev composer config --global github-oauth.github.com ${{ env.GH_TOKEN }}
          fi
      - run: ddev ci ${{ matrix.typo3 }} ${{ matrix.php }} ${{ matrix.composer }}

